### ISSUE TITLE
Express request.connection is undefined

### ISSUE THREAD

**Issue by artemave** [featurist/vinehill#2]
When some middleware (e.g. https://github.com/helmetjs/hsts) relies on `request.connection` being defined, the whole thing blows up here:

![image](https://cloud.githubusercontent.com/assets/23721/23317762/b0f41e96-fac7-11e6-8fa3-bfb3c8fe027d.png)

The fix seems to be simply to add `connection` property to vinehill fake request object (though I didn't run all the tests yet):

![image](https://cloud.githubusercontent.com/assets/23721/23317911/35a539d6-fac8-11e6-92f3-6a4d7f00a9d8.png)

**Comment by dereke** [comment]
awesome - thanks for the patch.
I made a few changes so that it also works in the browser - you can get this in 0.7.2
